name: state_manager_flutter
description: "The simplest state manager around"
github: "https://github.com/Yoeri-z/manager"


version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  state_manager:
    path: ../state_manager


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



