name: state_buddy
description:  The simplest state manager around for dart and flutter
version: 1.0.1
repository: "https://github.com/Yoeri-z/manager"

environment:
  sdk: ^3.2.0


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
